{{auth_error}}

<!-- From https://stackoverflow.com/questions/36728887/debugging-django-allauth-social-network-login-failure -->